server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: dev
  datasource:
    url: ${TWITTER_URL}
    username: ${TWITTER_USERNAME}
    password: ${TWITTER_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true