ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `username` VARCHAR(60);

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS  `enabled` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS  `account_not_expired` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS  `account_not_locked` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS  `credentials_not_expired` BOOLEAN NOT NULL DEFAULT true;
